const arrayList = [
    {
        id: '1',
        research: 'False',
        employeeCategory: 'Teaching',
        displayOrder: '12',
        groupHeading: 'Career Objective',
        edit: '',
        delete: '',
    },

    {
        id: '2',
        research: 'False',
        employeeCategory: 'Teaching',
        displayOrder: '12',
        groupHeading: 'Career Perception',
        edit: '',
        delete: '',
    },
    {
        id: '3',
        research: 'False',
        employeeCategory: 'Teaching',
        displayOrder: '12',
        groupHeading: 'idiologies',
        edit: '',
        delete: '',
    },
    {
        id: '4',
        research: 'True',
        employeeCategory: 'Research',
        displayOrder: '12',
        groupHeading: 'Career Objective',
        edit: '',
        delete: '',
    },
    {
        id: '5',
        research: 'True',
        employeeCategory: 'Teaching',
        displayOrder: '12',
        groupHeading: 'Career Objective',
        edit: '',
        delete: '',
    },
    {
        id: '6',
        research: 'True',
        employeeCategory: 'Teaching',
        displayOrder: '12',
        groupHeading: 'Career Objective',
        edit: '',
        delete: '',
    },
    {
        id: '7',
        research: 'True',
        employeeCategory: 'Teaching',
        displayOrder: '12',
        groupHeading: 'Career Objective',
        edit: '',
        delete: '',
    },
    {
        id: '8',
        research: 'True',
        employeeCategory: 'Teaching',
        displayOrder: '12',
        groupHeading: 'Career Objective',
        edit: '',
        delete: '',
    },
    {
        id: '9',
        research: 'True',
        employeeCategory: 'Teaching',
        displayOrder: '12',
        groupHeading: 'Career Objective',
        edit: '',
        delete: '',
    },
    {
        id: '10',
        research: 'True',
        employeeCategory: 'Teaching',
        displayOrder: '12',
        groupHeading: 'Policy Documents',
        edit: '',
        delete: '',
    },
    {
        id: '11',
        research: 'True',
        employeeCategory: 'Teaching',
        displayOrder: '12',
        groupHeading: 'Career Objective',
        edit: '',
        delete: '',
    },
]

export default arrayList